### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by NirOfir** [yhz-1995/cudaica_win#4]
Hi,

I'm thinking about using cudaica on a linux machine, and I was wondering if you got an answer from Fraimondo about the differences in step 3 between your implementations. I know this is a windows build but I was wondering about this, because this has to do with the basic CUDA code. I have an NVIDIA NVS 315 with 1 GB RAM (the data I plan to run ICA on is ~0.6 GB so I'm hoping this will be enough).

Thanks,
Nir

**Comment by CloudyDory** [comment]
Sorry, this is a very late reply, but up to now I have not received a reply from Fraimondo. Yet I have checked the C and CUDA code line-by-line and I believe the currently implementation is correct. There is a "numerical_test" folder in the CUDAICA plugin and it shows that CUDAICA and runICA produce the same result (except for some rounding errors) if they use the same random number generator and block separation method.

Best,
Yunhui

**Comment by NirOfir** [comment]
Thanks!
