### ISSUE TITLE
FastICA in the CUDAICA code for Matlab / EEGLAB

### ISSUE THREAD

**Issue by giddielle** [yhz-1995/cudaica_win#5]
Dear Yunhui,

I want to thank you for the implementation of CUDAICA in Matlab running on Windows 10 - it works perfectly in EEGLAB using an HP workstation and NVIDIA Quadro K6000 graphic card.

I’m wondering if you have also implemented FastICA in the CUDAICA code for Matlab / EEGLAB.

Thanks in advance.

Yours sincerely,

Giorgio Di Lorenzo

**Comment by CloudyDory** [comment]
Sorry for the late reply. No, CUDAICA only use the Infomax and extended Infomax ICA algorithms.

Best,
Yunhui
